[tool.black]
line-length = 88
target-version = ["py312"]
skip-string-normalization = false

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
force_sort_within_sections = true
lines_between_sections = 0

[tool.ruff]
line-length = 88
target-version = "py312"
lint.extend-select = ["E", "F", "I", "Q"]  # sample; tune to your preferences