[tool.black]
line-length = 88
target-version = ["py312"]
skip-string-normalization = false

[tool.ruff]
line-length = 88
target-version = "py312"
lint.extend-select = ["E", "F", "I", "Q"]  # sample; tune to your preferences